# Generated by Django 3.2.7 on 2022-10-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='Location',
            new_name='location',
        ),
    ]
