# Generated by Django 3.2.7 on 2022-10-26 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_location_ticket_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='date',
            new_name='event',
        ),
        migrations.AddField(
            model_name='ticket',
            name='position',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
