# Generated by Django 3.2.7 on 2022-10-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(default=333, max_length=254),
            preserve_default=False,
        ),
    ]
