# Generated by Django 3.2.7 on 2022-10-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='event',
            new_name='event_date',
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
