# Generated by Django 3.2.7 on 2022-10-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_price_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
