# Generated by Django 3.2.7 on 2022-10-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_ticket_price_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=8),
            preserve_default=False,
        ),
    ]
