# Generated by Django 3.2.7 on 2022-10-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_auto_20221030_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='price_adult',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price_child',
        ),
    ]
