# Generated by Django 3.2.7 on 2022-10-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_auto_20221031_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='adult_price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='child_price',
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
