# Generated by Django 3.2.7 on 2022-10-31 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_auto_20221031_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='price_adult',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price_child',
        ),
    ]
