# Generated by Django 3.2.7 on 2022-10-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='website',
            field=models.CharField(max_length=254),
        ),
    ]
