# Generated by Django 3.2.7 on 2022-10-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0002_alter_actor_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='website',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
